version: "3.8"

services:
  neuro-core:
    build: .
    environment:
      - RUST_LOG=info
      - AUTONOMOUS_MODE=1
    volumes:
      - ./data:/var/lib/neuro
    ports:
      - "8080:8080"
      - "9090:9090"

  monitoring:
    image: grafana/grafana
    ports:
      - "3000:3000"

    env_file:
      - .env.prod
