

services:
  neuro-core:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - AUTONOMOUS_MODE=true
    volumes:
      - ./config:/app/config

  monitoring:
    image: grafana/grafana
    ports:
      - "3000:3000"

    env_file:
      - .env.prod
